# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tamarin < Formula
  desc "An embedded scripting language for Go projects"
  homepage "https://github.com/cloudcmds/tamarin"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cloudcmds/tamarin/releases/download/v1.0.0/tamarin_Darwin_arm64.tar.gz"
      sha256 "bca0b7623c13a58ed6b5f0f3f168c7ac0936b923e2a43add44f4369df4400654"

      def install
        bin.install "tamarin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudcmds/tamarin/releases/download/v1.0.0/tamarin_Darwin_x86_64.tar.gz"
      sha256 "318f9b7ce93b4c64e6847bc48a97d1c86b15a03836961c9dcbc0ca1eec73f7f9"

      def install
        bin.install "tamarin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudcmds/tamarin/releases/download/v1.0.0/tamarin_Linux_arm64.tar.gz"
      sha256 "099a34ddf0ffc47a8150c3658460fe4ea00b8e81cb41e1142bc0e5a0dd14cbdd"

      def install
        bin.install "tamarin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudcmds/tamarin/releases/download/v1.0.0/tamarin_Linux_x86_64.tar.gz"
      sha256 "f2ee326a49ef4558b69582c799cf7002321c584fe30944f70ddc489e607c7def"

      def install
        bin.install "tamarin"
      end
    end
  end
end
