# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tamarin < Formula
  desc "An embedded scripting language for Go projects"
  homepage "https://github.com/cloudcmds/tamarin"
  version "0.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cloudcmds/tamarin/releases/download/v0.0.14/tamarin_Darwin_arm64.tar.gz"
      sha256 "79fcaa3809f4447579be6480f546af669f8ab18538d42ad04945f91f5aa66983"

      def install
        bin.install "tamarin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudcmds/tamarin/releases/download/v0.0.14/tamarin_Darwin_x86_64.tar.gz"
      sha256 "bd0cf9b9341fcfe7193bed4cf0d3dd04f97ee5ceb58f0863309c9987f476d682"

      def install
        bin.install "tamarin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudcmds/tamarin/releases/download/v0.0.14/tamarin_Linux_arm64.tar.gz"
      sha256 "dfce0f73479ea4f8c871e89f188b2e0f73764a614f0ff8f999721c2094db30e0"

      def install
        bin.install "tamarin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudcmds/tamarin/releases/download/v0.0.14/tamarin_Linux_x86_64.tar.gz"
      sha256 "a392f1531f2117e3d3a277698b1aeece1aff7fc62ffe29e4d2c767c55fc1a993"

      def install
        bin.install "tamarin"
      end
    end
  end
end
